name: publish

on:
  push

env:
  GO_VERSION: 1.16
  ROOT_IMAGE_NAME: ghcr.io/reliablyhq/walkthrough-slo-http-server

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - working-directory: server
      run: |
        docker build -t ${{ env.ROOT_IMAGE_NAME }}:${{ github.sha }} -t ${{ env.ROOT_IMAGE_NAME }}:latest --build-arg GO_VERSION=${{ env.GO_VERSION }} .
    - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
    - run: |
        docker push ${{ env.ROOT_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ROOT_IMAGE_NAME }}:latest