name: publish

on:
  push

env:
  GO_VERSION: 1.16
  ROOT_IMAGE_NAME: ghcr.io/reliablyhq/walkthrough-slo-http-server

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - working-directory: server
      run: |
        docker build -t ${{ env.ROOT_IMAGE_NAME }}:latest --build-arg GO_VERSION=${{ env.GO_VERSION }} .
    - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
    - run:
        docker tag ${{ env.ROOT_IMAGE_NAME }}:latest ${{ env.ROOT_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ROOT_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ROOT_IMAGE_NAME }}:latest
    - if: startsWith(github.ref, 'ref/tags/')
      env:
        VERSION_IMAGE_NAME: ${{ env.ROOT_IMAGE_NAME }}:$(echo ${{ env.github.ref }} | cut -c10-)
      run:
        docker tag ${{ env.ROOT_IMAGE_NAME }}:latest ${{ env.VERSION_IMAGE_NAME }}
        docker push ${{ env.VERSION_IMAGE_NAME }}