name: publish

on:
  push

env:
  GO_VERSION: 1.16
  ROOT_IMAGE_NAME: ghcr.io/reliablyhq/walkthrough-slo-http-server

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME_SHA: ${ROOT_IMAGE_NAME}:${{ github.sha }}
      IMAGE_NAME_LATEST: ${ROOT_IMAGE_NAME}:latest
    steps:
    - uses: actions/checkout@v2
    - working-directory: server
      run: |
        docker build -t ${IMAGE_NAME_SHA} -t ${IMAGE_NAME_LATEST} --build-arg GO_VERSION=${GO_VERSION} .
    - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
    - run: |
        docker push ${IMAGE_NAME_SHA}
        docker push ${IMAGE_NAME_LATEST}